paths:
  app_path_template: C:\Users\{username}\Desktop\baty_skrypty_programy\pyprogram\gotowe_programy\Czysty_pulpit
  desktop_path_template: C:\Users\{username}\Desktop
desktop_folder: Z Pulpitu
excluded_extensions:
- lnk
- '{ED7BA470-8E54-465E-825C-99712043E01C}'
- '{4234d49b-0245-4df3-b780-3893943456e1}'
- url
- ini
excluded_files: []
